services:
  frontend:
    image: ghcr.io/deineliebe/film-react-nest/frontend:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend-network
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend  
    env_file:
      - frontend/.env
    restart: unless-stopped

  backend:
    image: ghcr.io/deineliebe/film-react-nest/backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend-network
    depends_on:
      - postgres
    env_file:
      - backend/.env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - backend/.env
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - backend-network
    depends_on:
      - postgres
    env_file:
      - backend/.env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 79:80
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  backend-network:
  frontend-network:

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist: