services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend-net
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend  
    env_file:
      - frontend/.env
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend-net
    depends_on:
      - postgres
    env_file:
      - backend/.env
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: film_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - backend-net
    depends_on:
      - postgres
    env_file:
      - backend/.env
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist:

networks:
  backend-net:
  frontend-net: